version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./public:/var/www
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./public:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    restart: always
