version: '3'
services:
  nginx:
     restart: always
     image: nginx:latest
     ports:
       - "80:80"
     volumes:
       - ./public:/public
       - ./default.conf:/etc/nginx/conf.d/default.conf
     links:
       - php
  php:
      restart: always
      image: php:7.2-fpm
      volumes:
        - ./public:/public
